name: Post-Mortem-Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      # Only run when specific paths are modified
      - "incidents/html/*.html"
      # You can add more specific patterns as needed

jobs:
  claude-review-paths:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Please review this incident post-mortem following industry best practices for SaaS services.

            Note: The PR branch is already checked out in the current working directory.

            ## Review Criteria:

            ### 1. Required Sections & Completeness
            - **Summary**: Clear, concise overview of the incident
            - **Impact**: Quantitative metrics (affected users, services, duration, business impact)
            - **Root Cause**: Deep technical analysis identifying systematic causes
            - **Trigger**: Specific event or condition that initiated the failure
            - **Resolution**: Immediate mitigation and long-term fix steps
            - **Detection**: How the issue was identified (monitoring, alerts, user reports)
            - **Timeline**: Detailed chronological account with timestamps (prefer UTC)
            - **Action Items**: Specific, actionable tasks with owners to prevent recurrence
            - **Lessons Learned**: What went well, what went wrong, where we got lucky

            ### 2. Blameless Culture
            - Focuses on systematic causes, not individual blame
            - Assumes good intentions from all parties
            - Identifies process and system improvements, not people to "fix"

            ### 3. Root Cause Analysis Quality
            - Uses techniques like "Five Whys" to dig deeper
            - Distinguishes between trigger and underlying root cause
            - Identifies both technical and process failures
            - Examines why monitoring/alerting didn't catch the issue earlier

            ### 4. Actionability
            - Action items are specific and measurable
            - Each action has a clear owner
            - Actions address both immediate fixes and long-term prevention
            - Includes improvements to monitoring, testing, and deployment processes

            ### 5. Developer-Focused SaaS Considerations
            - API/service availability metrics clearly stated
            - Developer experience impact assessed
            - Documentation or communication gaps identified
            - Integration/dependency failures analyzed

            ### 6. Learning & Knowledge Sharing
            - Post-mortem provides educational value for the team
            - Insights are transferable to prevent similar incidents
            - Identifies trends across multiple incidents if applicable

            Please provide thorough feedback with inline comments on areas that need improvement,
            missing information, or where the analysis could be deeper. Highlight particularly
            well-written sections as examples of best practices.

          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*), Bash(gh pr diff:*), Bash(gh pr view:*)"
